url: http://gdgbirgunj.org/
#baseurl: /gdgbirgunj.org/

# Site settings
title: GDG Birgunj
email: dipesh@gdgbirgunj.org
description: "Google Developer Groups (GDGs) are for developers who are interested in Google’s developer technology; everything from the Android, Chrome, Drive, and Google Cloud platforms, to product APIs like the Cast API,Maps API, and YouTube API.

A GDG can take many forms — from just a few people getting together to watch our latest video, to large gatherings with demos and tech talks, to events like code sprints and hackathons.

However, at the core, GDGs are focused on developers and technical content, and the core audience should be developers."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 1DE9B6
  secondary: C6FF00 
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Dipesh Kumar
  pic: 2
  position: Community Lead, Developer<br><a href="mailto:dipesh@gdgbirgunj.org?Subject=Hello%20again" target="_top">Send Mail</a>
  social:
    - title: twitter
      url: http://twitter.com/aaryadip
    - title: facebook
      url: http://facebook.com/thedidip
    - title: google-plus
      url: http://google.com/+DipeshKumar

- name: Uday Gupta
  pic: 3
  position: Co-Ordinator<br><a href="mailto:udaygupta@gdgbirgunj.org?Subject=Hello%20again" target="_top">Send Mail</a>
  social:
    - title: twitter
      url: https://twitter.com/connectuday
    - title: facebook
      url: https://www.facebook.com/udaygupta01
    - title: google-plus
      url: https://plus.google.com/u/0/+UdayGupta01/posts

- name: Rambabu Mahato
  pic: 1
  position: Member
  social:
    - title: twitter
      url: #
    - title: facebook
      url: https://www.facebook.com/ram.honeyboy
    - title: google-plus
      url: https://plus.google.com/u/0/111115658793833402403/posts

#- name: Diana Petersen
#  pic: 3
#  position: Lead Developer
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: google-plus
#      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/gdgbirgunj
  - title: facebook
    url: http://facebook.com/gdgbirgunj
  - title: google-plus
    url: http://gplus.to/gdgbirgunj
  - title: youtube 
    url: http://youtube.com/gdgbirgunj
  - title: github
    url: http://github.com/gdgbirgunj

# Postal address (add as many lines as necessary)
address:
  - line: Birgunj, Parsa, Nepal
  - line: Earth, Near Mars, Milky Way Galaxy ;)

# Build settings
markdown: kramdown
permalink: pretty
