url: http://gdgbirgunj.org/
#baseurl: /gdgbirgunj.org/

# Site settings
title: GDG Birgunj
email: dipesh@gdgbirgunj.org
description: "We Are A Group Of Developers, Google Technology Enthusiasts & Googlers From Around Mid-Terai Region, Nepal.
We Discuss, Share Our Ideas, Experiences & Plan For Events, Meetups."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 1DE9B6
  secondary: C6FF00 
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Dipesh Kumar
  pic: 2
  position: Community Lead, Developer
  social:
    - title: twitter
      url: http://twitter.com/aaryadip
    - title: facebook
      url: http://facebook.com/thedidip
    - title: google-plus
      url: http://google.com/+DipeshKumar

- name: Uday Gupta
  pic: 3
  position: Co-Ordinator
  social:
    - title: twitter
      url: https://twitter.com/connectuday
    - title: facebook
      url: https://www.facebook.com/udaygupta01
    - title: google-plus
      url: https://plus.google.com/u/0/+UdayGupta01/posts

- name: Aditya Sharma
  pic: 1
  position: Java Developer<br>HCL Infosystem
  social:
    - title: twitter
      url: https://twitter.com/aditya9972
    - title: facebook
      url: https://www.facebook.com/ADITYASHARMA7299
    - title: google-plus
      url: https://plus.google.com/u/0/117580754794858726936/posts

- name: Nitesh Chaurasiya
  pic: 1
  position: Devloper<br>Tessolve SC
  social:
    - title: twitter
      url: https://twitter.com/NITESCHAURASIYA
    - title: facebook
      url: https://www.facebook.com/nitesh.chaurasiya
    - title: google-plus
      url: https://plus.google.com/u/0/106365601607685914904/posts

- name: Rambabu Mahato
  pic: 1
  position: Member, Developer<br>Teacher
  social:
#    - title: twitter
#      url: #
    - title: facebook
      url: https://www.facebook.com/ram.honeyboy
    - title: google-plus
      url: https://plus.google.com/u/0/111115658793833402403/posts


- name: YOU?
  pic: 1
  position: Find Your Name Here, Become Member Now
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/gdgbirgunj
  - title: facebook
    url: http://facebook.com/gdgbirgunj
  - title: google-plus
    url: http://gplus.to/gdgbirgunj
  - title: youtube 
    url: http://youtube.com/gdgbirgunj
  - title: github
    url: http://github.com/gdgbirgunj

# Postal address (add as many lines as necessary)
address:
  - line: Birgunj, Parsa, Nepal
  - line: Earth, Near Mars, Milky Way Galaxy ;)

# Build settings
markdown: kramdown
permalink: pretty
